import { Category, MenuItem } from "@/types/database";

export const INITIAL_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Meal Thalis", display_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: "cat-2", name: "Chicken", display_order: 2, is_active: true, created_at: new Date().toISOString() },
  { id: "cat-3", name: "Fish", display_order: 3, is_active: true, created_at: new Date().toISOString() },
  { id: "cat-4", name: "Mutton", display_order: 4, is_active: true, created_at: new Date().toISOString() },
  { id: "cat-5", name: "Rice & Biryani", display_order: 5, is_active: true, created_at: new Date().toISOString() },
  { id: "cat-6", name: "South Indian", display_order: 6, is_active: true, created_at: new Date().toISOString() },
  { id: "cat-7", name: "Veg", display_order: 7, is_active: true, created_at: new Date().toISOString() },
  { id: "cat-8", name: "Sides", display_order: 8, is_active: true, created_at: new Date().toISOString() },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // MEAL THALIS
  {
    id: "item-1",
    category_id: "cat-1",
    name: "Chicken Thali",
    description: "Boiled/White Rice, Chicken Gravy, 2 pcs Neer Dosa/Chapati, Chicken Sukka, 1 pcs Chicken Kabab, Veg Baiji, Pickle, Dry Fish Chutney",
    price: 249,
    image_url: "/images/menu/chicken-thali.jpg",
    availability_status: "available",
    is_trending: true,
    trending_order: 1,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[0],
  },
  {
    id: "item-2",
    category_id: "cat-1",
    name: "Fish Thali",
    description: "Boiled/White Rice, Neer Dosa/Chapati, Fish Fry, Veg Baiji, Fish Chutney",
    price: 249,
    image_url: "/images/menu/fish-thali.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[0],
  },
  {
    id: "item-3",
    category_id: "cat-1",
    name: "Veg Thali",
    description: "Boiled/White Rice, Dal/Rasam, Chapati, Veg Baiji, Dry Chutney, Papad, Pickle",
    price: 199,
    image_url: "/images/menu/veg-thali.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[0],
  },

  // RICE & BIRYANI
  {
    id: "item-4",
    category_id: "cat-5",
    name: "Ghee Rice Kabab",
    description: "Ghee rice served with juicy chicken kabab pieces, Dal and Green Gravy",
    price: 149,
    image_url: "/images/menu/ghee-rice-kabab.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[4],
  },
  {
    id: "item-5",
    category_id: "cat-5",
    name: "Biryani Combo",
    description: "Chicken Biryani served with salad, 2 pcs Kabab and Thums Up 200ml",
    price: 199,
    image_url: "/images/menu/biryani-combo.jpg",
    availability_status: "available",
    is_trending: true,
    trending_order: 2,
    preparation_time: 25,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[4],
  },
  {
    id: "item-13",
    category_id: "cat-5",
    name: "Donne Biryani",
    description: "A flavorful, signature South Indian rice dish",
    price: 249,
    image_url: "/images/menu/donne-biryani.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 25,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[4],
  },

  // SOUTH INDIAN
  {
    id: "item-6",
    category_id: "cat-6",
    name: "Neerdosa 1 Plate",
    description: "4 pieces Neerdosa",
    price: 80,
    image_url: "/images/menu/neer-dosa.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 10,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[5],
  },
  {
    id: "item-7",
    category_id: "cat-6",
    name: "Chapati 1 Plate",
    description: "4 pieces Chapati",
    price: 40,
    image_url: "/images/menu/chapati.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 10,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[5],
  },
  {
    id: "item-8",
    category_id: "cat-6",
    name: "Pundi Chicken Gassi",
    description: "Steamed rice dumplings (Pundi) served in rich coconut-based Chicken Gassi gravy",
    price: 199,
    image_url: "/images/menu/pundi-chicken-gassi.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[5],
  },
  {
    id: "item-9",
    category_id: "cat-6",
    name: "Kori Rotti Sukka",
    description: "Crispy rice wafers (Kori Rotti) with Chicken Sukka",
    price: 249,
    image_url: "/images/menu/kori-rotti-sukka.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[5],
  },

  // MUTTON
  {
    id: "item-10",
    category_id: "cat-4",
    name: "Mutton Ghee Roast",
    description: "Traditional Mangalorean style slow-cooked Mutton Ghee Roast",
    price: 499,
    image_url: "/images/menu/mutton-ghee-roast.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 30,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[3],
  },
  {
    id: "item-11",
    category_id: "cat-4",
    name: "Mutton Pepper Fry",
    description: "Dry Mutton stir-fry loaded with black pepper and spices",
    price: 499,
    image_url: "/images/menu/mutton-pepper-fry.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 25,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[3],
  },

  // CHICKEN
  {
    id: "item-12",
    category_id: "cat-2",
    name: "Chicken Sukka",
    description: "Dry, spicy chicken preparation with coconut and spices",
    price: 180,
    image_url: "/images/menu/chicken-sukka.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[1],
  },
  {
    id: "item-14",
    category_id: "cat-2",
    name: "Chicken Ghee Roast",
    description: "Spicy chicken stir-fry with crushed pepper",
    price: 249,
    image_url: "/images/menu/chicken-pepper-fry.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[1],
  },
  {
    id: "item-15",
    category_id: "cat-2",
    name: "1 Plate Chicken Kabab",
    description: "Juicy and flavorful chicken kababs served hot",
    price: 180,
    image_url: "/images/menu/chicken-kabab.jpg",
    availability_status: "available",
    is_trending: true,
    trending_order: 3,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[1],
  },

  // SIDES
  {
    id: "item-18",
    category_id: "cat-8",
    name: "Chicken Kabab",
    description: "Juicy coastal fried chicken kababs loaded with Mangalorean spices",
    price: 180,
    image_url: "/images/menu/chicken-kabab.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[7],
  },
  {
    id: "item-19",
    category_id: "cat-8",
    name: "Chicken Sukka (Side)",
    description: "Classic Mangalorean roasted chicken with grated coconut",
    price: 180,
    image_url: "/images/menu/chicken-sukka.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[7],
  },

  // VEG
  {
    id: "item-16",
    category_id: "cat-7",
    name: "Panner Pepper Fry",
    description: "Cubes of Panner tossed with crushed pepper and spices",
    price: 249,
    image_url: "/images/menu/paneer-pepper-fry.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[6],
  },
  {
    id: "item-17",
    category_id: "cat-7",
    name: "Panner Chilli",
    description: "Panner tossed in spicy chilli sauce with vegetables",
    price: 249,
    image_url: "/images/menu/paneer-chilli.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[6],
  },

  // FISH
  {
    id: "item-21",
    category_id: "cat-3",
    name: "Fish Fry",
    description: "Fresh coastal fish fry marinated with authentic Mangalorean spices",
    price: 249,
    image_url: "/images/menu/fish-fry.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[2],
  },
  {
    id: "item-22",
    category_id: "cat-6",
    name: "Parota 1 Plate",
    description: "1 Plate Parota",
    price: 60,
    image_url: "/images/menu/parota-1-plate.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 10,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[5],
  },
  {
    id: "item-23",
    category_id: "cat-6",
    name: "Neerdosa Chicken Sukka",
    description: "Classic Neerdosa served with Chicken Sukka",
    price: 149,
    image_url: "/images/menu/neerdosa-chicken-sukka.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 20,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[5],
  },
  {
    id: "item-24",
    category_id: "cat-2",
    name: "Chicken Pulimunchi",
    description: "Tangy and spicy Mangalorean chicken curry",
    price: 249,
    image_url: "/images/menu/chicken-pulimunchi.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 25,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[1],
  },
  {
    id: "item-25",
    category_id: "cat-2",
    name: "Chicken Banamanjal",
    description: "Authentic coastal chicken dish",
    price: 249,
    image_url: "/images/menu/chicken-banamanjal.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 25,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[1],
  },
  {
    id: "item-26",
    category_id: "cat-4",
    name: "Mutton Sukka",
    description: "Dry, spicy mutton preparation with coconut and spices",
    price: 399,
    image_url: "/images/menu/mutton-sukka.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 30,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[3],
  },
  {
    id: "item-27",
    category_id: "cat-5",
    name: "Panner Biriyani",
    description: "Flavorful biryani made with fragrant rice and paneer cubes",
    price: 149,
    image_url: "/images/menu/panner-biriyani.jpg",
    availability_status: "available",
    is_trending: false,
    trending_order: null,
    preparation_time: 25,
    created_at: new Date().toISOString(),
    category: INITIAL_CATEGORIES[4],
  }
];
